# Generated by Django 3.2.9 on 2021-11-18 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('Nome', models.CharField(max_length=300)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('professor', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=300)),
                ('descricao', models.TextField(max_length=500)),
                ('categoria', models.CharField(max_length=300)),
                ('datadepublicacao', models.DateTimeField(auto_now_add=True)),
                ('datadeedicao', models.DateTimeField(auto_now=True)),
                ('link', models.URLField(max_length=300)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=300)),
                ('descricao', models.TextField(max_length=500)),
                ('categoria', models.CharField(max_length=300)),
                ('datadepublicacao', models.DateTimeField(auto_now_add=True)),
                ('datadeedicao', models.DateTimeField(auto_now=True)),
                ('aulas', models.ManyToManyField(to='girls.aulas')),
                ('professores', models.ManyToManyField(related_name='profs', to=settings.AUTH_USER_MODEL)),
                ('usuarios', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
