# Generated by Django 3.2.9 on 2021-11-18 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
